Emscripten: Remove bogus BINARYEN_ROOT def which breaks build
As advised in the homebrew caveats:
 "and comment out BINARYEN_ROOT in ~/.emscripten after running `emcc` for the
  first time."

Otherwise, build fails with:
 "ERROR:root:Error in evaluating ~/.emscripten (at /Users/travis/.emscripten):
  'NoneType' object has no attribute 'startswith'"